receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 64
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1024
    spike_limit_mib: 256
  batch:
    send_batch_size: 8192
    send_batch_max_size: 10000
    timeout: 200ms

exporters:
  nop: {}

service:
  telemetry:
    logs:
      level: info
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [nop]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [nop]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [nop]
