{
 "title": "Apache Flink (2021) Dashboard for Job / Task Manager",
 "description": "Dashboard for Job Manager and Task Manager, prepared for versions: 1.12.X, 1.13.X",
 "tags": [
  "flink",
  "task manager",
  "job manager",
  "apache"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" },
   { "name": "tm_id", "label": "Task Manager", "query": { "query": "label_values(tm_id)" } },
   {
    "name": "jm_instance",
    "label": "Job Manager",
    "query": {
     "query": "label_values(flink_jobmanager_numRegisteredTaskManagers,instance)"
    }
   },
   {
    "name": "job_name",
    "label": "Job Name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured{tm_id=~\"$tm_id\"},job_name)"
    }
   },
   {
    "name": "task_name",
    "label": "Task Name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured{job_name=~\"$job_name\"},task_name)"
    }
   },
   { "name": "ad_hoc", "label": "Ad Hoc" }
  ]
 },
 "panels": [
  {
   "title": "Job Manager (JVM - CPU)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_CPU_Load{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_Status_JVM_CPU_Time{instance=~\"$jm_instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Threads_Count{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Manager (JVM - Memory Usage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Direct",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mapped",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Mapped_MemoryUsed{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Metaspace_Used{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Manager (JVM - Garbage Collector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mark Sweep Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_GarbageCollector_PS_MarkSweep_Time",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scavenge Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_Status_JVM_GarbageCollector_PS_Scavenge_Time[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Manager (Slots & Jobs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Managers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_numRegisteredTaskManagers{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Task Slots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_taskSlotsTotal{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Available Task Slots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_taskSlotsAvailable{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Runnings Jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_numRunningJobs{instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Job Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_numRestarts{job_name=~\"$job_name\", instance=~\"$jm_instance\"}",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    },
    {
     "title": "Job Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_fullRestarts{job_name=~\"$job_name\", instance=~\"$jm_instance\"}",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    },
    {
     "title": "Job Restartine Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_restartingTime{job_name=~\"$job_name\", instance=~\"$jm_instance\"}",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    },
    {
     "title": "Job Uptime",
     "type": "stat",
     "gridPos": { "h": 10, "w": 21, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_uptime{job_name=~\"$job_name\", instance=~\"$jm_instance\"}",
       "legendFormat": "{{job_id}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime Derscription",
     "type": "text",
     "gridPos": { "h": 10, "w": 3, "x": 21, "y": 20 },
     "options": {
      "content": "# Uptime Description\n\n| Color | Status|\n|---|---|\n| Green | < 1 Hour |\n| Yellow | >= 1 Hour  |\n| Orange | >= 6 Hours |\n| Purple | >= 1 Day |\n| Red | >= 3 days |\n"
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Job Manager (Checkpoints)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_job_totalNumberOfCheckpoints{job_name=~\"$job_name\", instance=~\"$jm_instance\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    },
    {
     "title": "Completed Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 5 },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_job_numberOfCompletedCheckpoints{job_name=~\"$job_name\", instance=~\"$jm_instance\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    },
    {
     "title": "In Progress Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_job_numberOfInProgressCheckpoints{job_name=~\"$job_name\", instance=~\"$jm_instance\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    },
    {
     "title": "Failed Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 5 },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_job_numberOfFailedCheckpoints{job_name=~\"$job_name\", instance=~\"$jm_instance\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointSize{job_name=~\"$job_name\", instance=~\"$jm_instance\"}",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration{job_name=~\"$job_name\", instance=~\"$jm_instance\"}",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "xx{job_name=~\"$job_name\", instance=~\"$jm_instance\"}",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (JVM - CPU)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_CPU_Load{tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_Status_JVM_CPU_Time{tm_id=~\"$tm_id\"}[1m])",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Threads_Count{tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (JVM - Memory Usage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Non Heap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Direct",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Mapped",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Mapped_MemoryUsed{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Metaspace_Used{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (JVM - Garbage Collector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Young Generation Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Old Generation Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Memory - Flink)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Managed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Flink_Memory_Managed_Used{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Memory - Shuffle Netty)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_TotalMemory{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Total Memory Segments",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_TotalMemorySegments{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_UsedMemory{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_AvailableMemory{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Used Memory Segments",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_UsedMemorySegments{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Available Memory Segments",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_AvailableMemorySegments{tm_id=~\"$tm_id\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Diag)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Is Back Pressured",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_isBackPressured{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Idle Time Ms (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_idleTimeMsPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Checkpoint Alignment Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_checkpointStartDelayNanos{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Checkpoint Alignment Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_checkpointAlignmentTime{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager  (Job Task - General)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Buffers in Local",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numBuffersInLocal{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers in Local (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBuffersInLocalPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers in Remote",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numBuffersInRemote{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers in Remote (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBuffersInRemotePerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numBuffersOut{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers Out (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBuffersOutPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numBytesIn{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBytesInPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In Local",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numBytesInLocal{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In Local (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBytesInLocalPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In Remote",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numBytesInRemote{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In Remote (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBytesInRemotePerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes Out",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numBytesOut{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes Out (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBytesOutPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Records In",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numRecordsIn{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numRecordsInPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Records Out",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numRecordsOut{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes Out (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numRecordsOutPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Buffers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "In Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inPoolUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inputQueueLength{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Exclusive Buffers Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inputExclusiveBuffersUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Out Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_outPoolUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Output Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_outputQueueLength{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Floating Buffers Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inputFloatingBuffersUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Operator)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Late Records Dropped",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_numLateRecordsDropped",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Records In",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_operator_numRecordsIn{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Records Out (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 9, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_operator_numRecordsInPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Records In",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 14, "y": 14 },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_operator_numRecordsOut{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Num Records Out (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 14 },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Shuffle Netty)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputQueueLength{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Output Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_outputQueueLength{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "In Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inPoolUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Out Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_outPoolUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Floating Buffers Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputFloatingBuffersUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Exclusive Buffers Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputExclusiveBuffersUsage{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Buffers In Local",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInLocal{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Buffers In Local (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInLocalPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Buffers In Remote",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInRemote{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Num Buffers In Remote (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInRemotePerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Num Bytes In Local",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInLocal{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Bytes In Local (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInLocalPerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Bytes In Remote",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInRemote{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Bytes In Remote (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInRemotePerSecond{tm_id=~\"$tm_id\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  }
 ]
}